import { SalesTeamMember, SupportTeamMember } from "./types";

// Dados para a equipe de vendas
export const salesTeamData: SalesTeamMember[] = [
  {
    id: 1,
    name: "Ana Silva",
    avatar: "",
    role: "Vendedora Sênior",
    sales: 156000,
    deals: 28,
    target: 180000,
    completion: 87,
    awards: ["Top Seller Q1", "Maior Ticket Médio"],
    previousPosition: 2,
    trend: "up",
  },
  {
    id: 2,
    name: "Carlos Oliveira",
    avatar: "",
    role: "Vendedor Pleno",
    sales: 142000,
    deals: 32,
    target: 150000,
    completion: 95,
    awards: ["Mais Negócios Fechados"],
    previousPosition: 3,
    trend: "up",
  },
  {
    id: 3,
    name: "Juliana Costa",
    avatar: "",
    role: "Vendedora Sênior",
    sales: 178000,
    deals: 24,
    target: 180000,
    completion: 99,
    awards: ["Melhor Taxa de Conversão"],
    previousPosition: 1,
    trend: "down",
  },
  {
    id: 4,
    name: "Ricardo Almeida",
    avatar: "",
    role: "Vendedor Pleno",
    sales: 129000,
    deals: 26,
    target: 150000,
    completion: 86,
    awards: [],
    previousPosition: 4,
    trend: "same",
  },
  {
    id: 5,
    name: "Fernanda Lima",
    avatar: "",
    role: "Vendedora Júnior",
    sales: 98000,
    deals: 18,
    target: 100000,
    completion: 98,
    awards: ["Revelação do Trimestre"],
    previousPosition: 5,
    trend: "same",
  }
];

// Dados para a equipe de suporte
export const supportTeamData: SupportTeamMember[] = [
  {
    id: 1,
    name: "Marcos Santos",
    avatar: "",
    role: "Atendente Sênior",
    tickets: 245,
    resolution: 92,
    satisfaction: 97,
    target: 240,
    completion: 102,
    awards: ["Melhor Satisfação do Cliente"],
    previousPosition: 1,
    trend: "same",
  },
  {
    id: 2,
    name: "Patricia Ferreira",
    avatar: "",
    role: "Atendente Plena",
    tickets: 228,
    resolution: 89,
    satisfaction: 95,
    target: 220,
    completion: 104,
    awards: ["Resolução Mais Rápida"],
    previousPosition: 3,
    trend: "up",
  },
  {
    id: 3,
    name: "Roberto Gomes",
    avatar: "",
    role: "Atendente Sênior",
    tickets: 210,
    resolution: 94,
    satisfaction: 96,
    target: 240,
    completion: 88,
    awards: ["Maior Taxa de Resolução no 1° Contato"],
    previousPosition: 2,
    trend: "down",
  },
  {
    id: 4,
    name: "Camila Duarte",
    avatar: "",
    role: "Atendente Plena",
    tickets: 215,
    resolution: 91,
    satisfaction: 94,
    target: 220,
    completion: 98,
    awards: [],
    previousPosition: 4,
    trend: "same",
  },
  {
    id: 5,
    name: "Lucas Martins",
    avatar: "",
    role: "Atendente Júnior",
    tickets: 180,
    resolution: 87,
    satisfaction: 92,
    target: 180,
    completion: 100,
    awards: ["Revelação do Mês"],
    previousPosition: 6,
    trend: "up",
  }
];